MSAL Angular SPA
Azure-Samples/ms-identity-docs-code-javascript pull request #15
Opened 2022-03-16 16:12 UTC by skabou

Initial import DOCS-CODE-0022

2022-03-16 16:14 UTC, skabou commented
This should look familiar to you 😄  ckittel

2022-03-16 16:31 UTC, ckittel approved these changes
LGTM (again ;)), good for CD.

2022-03-17 20:07 UTC, ckittel commented
@skabou , I added @mmacy as a reviewer since you mentioned in standup this morning that this was ready for review by him.  Please adjust expectations if that's not the case.

2022-03-17 21:22 UTC, skabou commented
Thanks @ckittel !

2022-03-19 17:06 UTC, mmacy requested changes
@skabou Thanks, Jason. A few changes (clarifications, mostly) requested.

2022-03-19 17:06 UTC, mmacy commented on angular-spa/README.md
> +- MSALBroadcastService is used to consume events emitted by MSAL
Which event(s) and why?

2022-03-19 17:06 UTC, mmacy commented on angular-spa/README.md
> +- MSALInterceptor is provided by MSAL Angular to automatically acquire tokens for protected resources
Access tokens, ID tokens, or both?

2022-03-19 17:06 UTC, mmacy commented on angular-spa/README.md
> +- HttpClient is used to perform an HTTP GET request against Graph with the user's token
```suggestion
- HttpClient is used to issue an HTTP GET request to Microsoft Graph with user's access token.
```

2022-03-19 17:06 UTC, mmacy commented on angular-spa/README.md
> +This Angular application uses the Angular MSAL v2 library to authenticate a user and then makes a request to the Graph API as the authenticated user.
```suggestion
This Angular web application uses the Angular MSAL v2 library to authenticate a user and then makes a request to the Microsoft Graph API as the authenticated user to retrieve their user profile data.
```

2022-03-19 17:06 UTC, mmacy commented on angular-spa/README.md
> +## About the code
Please note the filenames each of these are used in.

2022-03-19 17:06 UTC, mmacy commented on angular-spa/README.md
> +- MSALGuard is used to protect routes
```suggestion
- MSALGuard is used to protect the web app's routes.
```

Also, which routes?

2022-03-22 01:21 UTC, skabou commented
ok round 2... Think I covered everything.  Please review when ready! @mmacy

2022-03-25 14:47 UTC, merged