Add React single-page sample app
Azure-Samples/ms-identity-docs-code-javascript pull request #6
Opened 2022-01-26 04:14 UTC by Dickson-Mwendia

## Purpose

*  This PR is for #DOCS-CODE-023 - React single-page app . It imports the sample from https://github.com/Azure-Samples/ms-identity-javascript-react-docs 

Cc: @dhruvchand @ckittel @henrymbuguakiarie @mmacy

2022-01-26 16:16 UTC, ckittel requested changes
Glad to see this bring added to the repo!  Here are some things that ideally we can fix before import, that would be great.  If you can't, please add a backlog item for each to address later.

2022-01-26 16:16 UTC, ckittel commented on react-single-page-app/README.md
> +
Can you add to the backlog that this needs to be updated to the new style?  Not a blocker for this import, but should be done soon.

2022-01-26 16:16 UTC, ckittel commented on react-single-page-app/src/index.js
> +      clientId: "034ff080-d093-433d-915c-4f12ae03f100"
Can you please replace this with our standard placeholder text (seen in other examples)

2022-01-26 16:16 UTC, ckittel commented on react-single-page-app/src/index.js
> +  } catch (e) {
Should this be only a specific exception?  This seems really broad for this specific followup code in the catch.

2022-01-26 16:16 UTC, ckittel commented on react-single-page-app/src/index.js
> +  const response = await fetch(`${MICROSOFT_GRAPH_URL}/me`, {
Inline `https://graph.microsoft.com/v1.0` to simplify the code.  (This is learnings from other examples we have built)

2022-01-26 16:16 UTC, ckittel commented on react-single-page-app/src/index.js
> +  const bearer = `Bearer ${await getGraphToken(msalInstance, accounts)}`;
Inline the code to get the graph token here in this function. (This is learnings/requirements from other examples we have built)

2022-01-26 16:16 UTC, ckittel commented on react-single-page-app/src/index.js
> +    scopes: ["User.Read", "openid", "profile"],
Should only need `User.Read` -- the rest are automatic (and not able to be changed anyhow)

2022-01-26 16:16 UTC, ckittel commented on react-single-page-app/src/index.js
> +    return accessToken;
Simplification.

```suggestion
    return await msalInstance.acquireTokenSilent(tokenRequest);
```

2022-01-26 16:16 UTC, ckittel commented on react-single-page-app/src/index.js
> +    return accessToken;
Simplification.
```suggestion
    return await msalInstance.acquireTokenPopup(tokenRequest);
```

2022-01-26 16:16 UTC, ckittel commented on react-single-page-app/src/index.js
> +  const { instance, accounts } = useMsal();
Suggestion, use a more meaningful name than `instance`.

2022-08-22 18:04 UTC, mmacy commented
@Dickson-Mwendia I just merged #23 from @henrymbuguakiarie but now wondering if we need to implement the review changes here into that. Maybe I should have merged this one?

Not sure - can you two sort it out and let me know?

2022-08-26 16:06 UTC, closed without merging